### ISSUE TITLE
Error in v3

### ISSUE THREAD

**Issue by LucasZdv** [inetis-ch/oc-CustomGoogleSearch-plugin#10]
![download (1)](https://user-images.githubusercontent.com/7346040/192130496-7a04d00a-c672-4f31-ba69-f4855e75b6f0.png)

**Comment by Fl0Cri** [comment]
Hi, thanks for reporting this. We released a new version (1.0.7), this should fix the issue.

**Comment by LucasZdv** [comment]
Thank you very much, Its works!!!!
