### ISSUE TITLE
Hard limit parameters?

### ISSUE THREAD

**Issue by zlobec** [inetis-ch/oc-CustomGoogleSearch-plugin#8]
As per limitation of the API, should there be hard limits for query parameters?

https://developers.google.com/custom-search/v1/reference/rest/v1/cse/list

https://github.com/inetis-ch/oc-CustomGoogleSearch-plugin/blob/854f38db9c742c0e62cb4574e32cb2b2cf68eebf/components/SearchResults.php#L67

Should this be hard limited, since users might put in more then 10 in search results... and the query returns an error if more than 10?

`$this->resultPerPage = min(10, $this->property('resultPerPage'));`

And same here (have not tested this yet):
https://github.com/inetis-ch/oc-CustomGoogleSearch-plugin/blob/854f38db9c742c0e62cb4574e32cb2b2cf68eebf/components/SearchResults.php#L99

Or add validation to resultPerPage parameter like:
```
                'validationPattern' => '^([1-9]|10)$',
                'validationMessage' => 'The max result per page is limited to max 10 by Google API.',
```

**Comment by Fl0Cri** [comment]
New version with #9 released
